name: Main branch workflow

on:
  push:
    branches:
      - 'master'

jobs:
  publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3